import { inter } from "@/components/fonts/font";
import "./globals.css";
// import styles from "./global.css"
// import { Inter } from 'next/font/google' 


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
